// EnsoAI Stop Hook - Sends precise agent completion notifications
// Auto-generated by EnsoAI - Do not edit manually
// Requires Node.js in PATH

const fs = require('fs');
const path = require('path');
const http = require('http');

const IDE_DIR = 'C:/Users/Lathan/.claude/ide';

async function main() {
  // Read JSON from stdin
  let input = '';
  process.stdin.setEncoding('utf8');
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  let sessionId;
  try {
    const data = JSON.parse(input);
    sessionId = data.session_id;
  } catch {
    process.exit(0);
  }

  if (!sessionId) {
    process.exit(0);
  }

  // Find EnsoAI lockfile
  if (!fs.existsSync(IDE_DIR)) {
    process.exit(0);
  }

  const lockfiles = fs.readdirSync(IDE_DIR).filter(f => f.endsWith('.lock'));
  for (const lockfile of lockfiles) {
    try {
      const content = JSON.parse(fs.readFileSync(path.join(IDE_DIR, lockfile), 'utf-8'));
      if (content.ideName === 'EnsoAI') {
        const port = path.basename(lockfile, '.lock');
        // Send POST request
        const postData = JSON.stringify({ session_id: sessionId });
        const req = http.request({
          hostname: '127.0.0.1',
          port: parseInt(port),
          path: '/agent-stop',
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(postData),
          },
          timeout: 2000,
        });
        req.on('error', () => {});
        req.write(postData);
        req.end();
        break;
      }
    } catch {
      // Ignore errors, try next lockfile
    }
  }
}

main().catch(() => process.exit(0));
